# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MedScreen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'ExyteChat'

  # Pods for MedScreen

end
